### PR TITLE
AWS fixes

### LINKED ISSUE #442: Parse error with config used by aws cli v2 (cli_pager)
Hey there,

Terraformer fails to parse ~/.aws/config files that contain the `cli_pager=` argument.

Having this config:

```
[default]
region = eu-west-1
output = json
cli_pager =
```

terraformer fails with:
```
failed to load shared config file, ~/.aws/config, INIParseError: invalid state with ASTKind { {4 NONE 0 [61]} true [{expr {1 STRING 0 [99 108 105 95 112 97 103 101 114]} true []}]} and TokenType {0 NONE 0 []}
```
By removing the cli_pager line, it works, but I feel like it should work with it as well :)

### LINKED ISSUE #463: AWS Glue Table Duplicate resource found error
A duplicate error occurs when there is a Glue table with the same name is in a different Glue database in the same region.  This is a similar issue as #296.

**Database A**
* Table build_account
* Table prod_account

**Database B**
* Table stage_account
* Table build_account

**Using:**
terraformer version v0.8.7
terraform-provider-aws version v2.55.0

**Error Message:**
2020/03/30 11:08:32 [ERR]: duplicate resource found: aws_glue_catalog_table.tfer--build_account

### LINKED ISSUE #466: Not all the objets are imported from AWS CloudWatch
I have multiple metric alarms but I only got imported some of them.

Maybe it's not related but could be seems to be some kind of limit in the result file, I only got 1100 lines max in cloudwatch_metric_alarm.tf.

I'm using version 0.8.7 on macOS 10.15 with AWS Provider 2.55.

### PR DESCRIPTION
**Pull request by meshuga**
Started adding pagination to AWS services, glue table name fix, AWS SDK upgrade

closes #466
closes #463
closes #442

### CODE REVIEW

File: tests/aws/main.go [hunk 1]
```diff
@@ -30,7 +30,7 @@ func main() {
 		"import",
 		"aws",
 		"--regions=ap-southeast-1",
-		"--resources=vpc,sg",
+		"--resources=api_gateway",
```
Comment (chenrui333) [inline tests/aws/main.go:33]: this change seems not quite necessary.
